server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yun-xi/config-repo
          username: 987159036@qq.com
          password: 651867Xie
          basedir: D:\basedir
  rabbitmq:
    host: 47.101.151.28
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    prefer-ip-address: true  #  将自身ip注册到Eureka中
    instance-id:  ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})  # 自定义显示方式 项目名称（ip:port）
  client:
    service-url:
      defaultZone: http://47.101.151.28:8761/eureka
# 暴露全部的接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

