# 该服务既是服务端(server)，也是客户端(client)，因此将它注册到自己
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    # 表明自己是个eurekaServer
    register-with-eureka: false
    fetch-registry: false
  # 关闭上线率低的为在线（开发环境设置，生产环境不要关闭）
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
#server:
#  port: 8761